proxies:
- name: "ğŸ“± ĞĞ½Ñ‚Ğ¸Ğ±Ğ»Ğ¾Ğº 65 | Fast"
  type: vless
  server: '95.163.249.45'
  port: 443
  uuid: '7503171c-a602-4663-b82f-88aaf1ce9992'
  udp: true
  tls: true
  servername: 'api-maps.yandex.ru'
  flow: 'xtls-rprx-vision'
  skip-cert-verify: false
  client-fingerprint: 'edge'
  network: 'tcp'
  reality-opts:
    public-key: '10rVZPoOUP1TlQviIAsQ_jAROX0fRQxH0C92nq_zGQc'
    short-id: '43dcff53849b81e6'

- name: "ğŸ“± ĞĞ½Ñ‚Ğ¸Ğ±Ğ»Ğ¾Ğº 82 | Fast, RTK"
  type: vless
  server: '176.109.105.79'
  port: 10167
  uuid: '7503171c-a602-4663-b82f-88aaf1ce9992'
  udp: true
  tls: true
  servername: 'ozon.ru'
  flow: 'xtls-rprx-vision'
  skip-cert-verify: false
  client-fingerprint: 'qq'
  network: 'tcp'
  reality-opts:
    public-key: '10rVZPoOUP1TlQviIAsQ_jAROX0fRQxH0C92nq_zGQc'
    short-id: '43dcff53849b81e6'

- name: "ğŸ“± ĞĞ½Ñ‚Ğ¸Ğ±Ğ»Ğ¾Ğº 128 | Social"
  type: vless
  server: '217.16.20.134'
  port: 443
  uuid: '0f6c83bc-34ba-4ca1-96e6-08b3620cbce5'
  udp: true
  tls: true
  servername: 'www.vk.com'
  skip-cert-verify: false
  client-fingerprint: 'firefox'
  network: 'tcp'
  reality-opts:
    public-key: '24lsP7iRzgT7pMhCprlmHUB6_mbR17Pxc6P0R29f-Rk'
    short-id: '35e15c94'

- name: "ğŸ‡¦ğŸ‡± Albania â€” #130"
  type: vless
  server: '78.159.131.23'
  port: 443
  uuid: 'abff54b1-a5a6-46a6-a202-08452fd07ae7'
  udp: true
  tls: true
  servername: 'al.cdn.stun.su'
  flow: 'xtls-rprx-vision'
  skip-cert-verify: false
  client-fingerprint: 'chrome'
  network: 'tcp'
  reality-opts:
    public-key: 'su3dq3BDLDkX-jIjq3GyVUXwqzD7CNVYzKtOcO4HQ24'
    short-id: 'bbfb4f7a53e22dd3'

- name: "ğŸ‡¦ğŸ‡± Albania â€” #128"
  type: vless
  server: '185.177.238.57'
  port: 443
  uuid: '28c69927-fc08-43c2-a09f-e9c7bb1529bb'
  udp: true
  tls: true
  servername: 'al.cdn.stun.su'
  flow: 'xtls-rprx-vision'
  skip-cert-verify: false
  client-fingerprint: 'chrome'
  network: 'tcp'
  reality-opts:
    public-key: 'su3dq3BDLDkX-jIjq3GyVUXwqzD7CNVYzKtOcO4HQ24'
    short-id: '3846b9259d66cc64'

- name: "ğŸ“± ĞĞ½Ñ‚Ğ¸Ğ±Ğ»Ğ¾Ğº 71 | Fast"
  type: vless
  server: '178.154.221.124'
  port: 443
  uuid: '7503171c-a602-4663-b82f-88aaf1ce9992'
  udp: true
  tls: true
  servername: 'ads.x5.ru'
  flow: 'xtls-rprx-vision'
  skip-cert-verify: false
  client-fingerprint: 'edge'
  network: 'tcp'
  reality-opts:
    public-key: '10rVZPoOUP1TlQviIAsQ_jAROX0fRQxH0C92nq_zGQc'
    short-id: '43dcff53849b81e6'

- name: "ğŸ‡¦ğŸ‡± Albania â€” #127"
  type: vless
  server: '78.159.131.48'
  port: 443
  uuid: '28c69927-fc08-43c2-a09f-e9c7bb1529bb'
  udp: true
  tls: true
  servername: 'al.cdn.stun.su'
  flow: 'xtls-rprx-vision'
  skip-cert-verify: false
  client-fingerprint: 'chrome'
  network: 'tcp'
  reality-opts:
    public-key: 'su3dq3BDLDkX-jIjq3GyVUXwqzD7CNVYzKtOcO4HQ24'
    short-id: '616dbb46ca288c32'

- name: "ğŸ“± ĞĞ½Ñ‚Ğ¸Ğ±Ğ»Ğ¾Ğº 66 | Fast"
  type: vless
  server: '95.163.250.190'
  port: 8443
  uuid: '7503171c-a602-4663-b82f-88aaf1ce9992'
  udp: true
  tls: true
  servername: 'sun6-21.userapi.com'
  flow: 'xtls-rprx-vision'
  skip-cert-verify: false
  client-fingerprint: 'qq'
  network: 'tcp'
  reality-opts:
    public-key: '10rVZPoOUP1TlQviIAsQ_jAROX0fRQxH0C92nq_zGQc'
    short-id: '43dcff53849b81e6'

- name: "ğŸ“± ĞĞ½Ñ‚Ğ¸Ğ±Ğ»Ğ¾Ğº 83 | Fast, RTK, Social"
  type: vless
  server: '176.108.242.117'
  port: 10167
  uuid: '7503171c-a602-4663-b82f-88aaf1ce9992'
  udp: true
  tls: true
  servername: 'eh.vk.com'
  flow: 'xtls-rprx-vision'
  skip-cert-verify: false
  client-fingerprint: 'qq'
  network: 'tcp'
  reality-opts:
    public-key: '10rVZPoOUP1TlQviIAsQ_jAROX0fRQxH0C92nq_zGQc'
    short-id: '43dcff53849b81e6'

- name: "210 | ğŸ³ï¸ VK | ğŸ‡·ğŸ‡º Russia | VLESS | TG: @YoutubeUnBlockRu"
  type: vless
  server: '92.53.120.70'
  port: 443
  uuid: 'c495cf08-e046-4311-aa4b-82cc16576992'
  udp: true
  tls: true
  servername: 'm.vk.com'
  skip-cert-verify: false
  network: 'grpc'
  reality-opts:
    public-key: 'yt24_imlgFLKEGm__E789B9pwuMXK7UKJ9ITTJuxuyo'
    short-id: '84ba23f147ad7a15'
  grpc-opts:
    grpc-service-name: 'm.vk.com'

- name: "[OpenRay] ğŸ‡³ğŸ‡´ NO-5"
  type: trojan
  server: '217.170.194.222'
  port: 13580
  password: 'ZyX#rcLFldaPKHUC7NYm'
  udp: true
  tls: true
  servername: 'aspryonktg.mthjfbiay.click'
  skip-cert-verify: true

- name: "[OpenRay] ğŸ‡·ğŸ‡º RU-162"
  type: vless
  server: '5.129.193.147'
  port: 443
  uuid: 'a888c6da-33b0-480c-a40a-0e94f4eb9c48'
  udp: true
  tls: true
  servername: 'eh.vk.com'
  flow: 'xtls-rprx-vision'
  skip-cert-verify: false
  client-fingerprint: 'chrome'
  network: 'tcp'
  reality-opts:
    public-key: 'mza5Hn1aolSz65qu-UwvBP3oesxMe25r11o4nxvikF0'
    short-id: '93ae75024604f796'

- name: "[OpenRay] ğŸ‡·ğŸ‡º RU-164"
  type: vless
  server: '89.169.137.193'
  port: 443
  uuid: '2c8adcaa-e428-4cea-9c88-e88166651ab3'
  udp: true
  tls: true
  servername: 'eh.vk.com'
  flow: 'xtls-rprx-vision'
  skip-cert-verify: false
  client-fingerprint: 'chrome'
  network: 'tcp'
  reality-opts:
    public-key: 'mza5Hn1aolSz65qu-UwvBP3oesxMe25r11o4nxvikF0'
    short-id: 'd1579a8745398e34'

proxy-groups: 
- name: PROXY
  type: select
  url: http://cp.cloudflare.com/generate_204
  expected-status: 204
  interval: 300
  icon: https://i.imgur.com/B3HrpPC.png
  proxies:
    - auto
    - "ğŸ“± ĞĞ½Ñ‚Ğ¸Ğ±Ğ»Ğ¾Ğº 65 | Fast"
    - "ğŸ“± ĞĞ½Ñ‚Ğ¸Ğ±Ğ»Ğ¾Ğº 82 | Fast, RTK"
    - "ğŸ“± ĞĞ½Ñ‚Ğ¸Ğ±Ğ»Ğ¾Ğº 128 | Social"
    - "ğŸ‡¦ğŸ‡± Albania â€” #130"
    - "ğŸ‡¦ğŸ‡± Albania â€” #128"
    - "ğŸ“± ĞĞ½Ñ‚Ğ¸Ğ±Ğ»Ğ¾Ğº 71 | Fast"
    - "ğŸ‡¦ğŸ‡± Albania â€” #127"
    - "ğŸ“± ĞĞ½Ñ‚Ğ¸Ğ±Ğ»Ğ¾Ğº 66 | Fast"
    - "ğŸ“± ĞĞ½Ñ‚Ğ¸Ğ±Ğ»Ğ¾Ğº 83 | Fast, RTK, Social"
    - "210 | ğŸ³ï¸ VK | ğŸ‡·ğŸ‡º Russia | VLESS | TG: @YoutubeUnBlockRu"
    - "[OpenRay] ğŸ‡³ğŸ‡´ NO-5"
    - "[OpenRay] ğŸ‡·ğŸ‡º RU-162"
    - "[OpenRay] ğŸ‡·ğŸ‡º RU-164"

- name: auto
  type: url-test
  url: http://cp.cloudflare.com/generate_204
  expected-status: 204
  interval: 300
  tolerance: 150
  lazy: true
  proxies:
    - "ğŸ“± ĞĞ½Ñ‚Ğ¸Ğ±Ğ»Ğ¾Ğº 65 | Fast"
    - "ğŸ“± ĞĞ½Ñ‚Ğ¸Ğ±Ğ»Ğ¾Ğº 82 | Fast, RTK"
    - "ğŸ“± ĞĞ½Ñ‚Ğ¸Ğ±Ğ»Ğ¾Ğº 128 | Social"
    - "ğŸ‡¦ğŸ‡± Albania â€” #130"
    - "ğŸ‡¦ğŸ‡± Albania â€” #128"
    - "ğŸ“± ĞĞ½Ñ‚Ğ¸Ğ±Ğ»Ğ¾Ğº 71 | Fast"
    - "ğŸ‡¦ğŸ‡± Albania â€” #127"
    - "ğŸ“± ĞĞ½Ñ‚Ğ¸Ğ±Ğ»Ğ¾Ğº 66 | Fast"
    - "ğŸ“± ĞĞ½Ñ‚Ğ¸Ğ±Ğ»Ğ¾Ğº 83 | Fast, RTK, Social"
    - "210 | ğŸ³ï¸ VK | ğŸ‡·ğŸ‡º Russia | VLESS | TG: @YoutubeUnBlockRu"
    - "[OpenRay] ğŸ‡³ğŸ‡´ NO-5"
    - "[OpenRay] ğŸ‡·ğŸ‡º RU-162"
    - "[OpenRay] ğŸ‡·ğŸ‡º RU-164"